
import { Category, Gender, Product } from './types';

export const UNILAG_HOSTELS = [
  "Amina Hall", "Biobaku Hall", "El-Kanemi Hall", "Fagunwa Hall", 
  "Honours Hall", "Jaja Hall", "Kofo Ademola Hall", "Madam Tinubu Hall", 
  "Makama Bida Hall", "Mariere Hall", "Moremi Hall", "New Hall", 
  "Queen Amina Hall", "Sodeinde Hall"
];

export const DELIVERY_FEE = 600;

export const ACCOUNT_DETAILS = {
  bank: "Opay",
  accountName: "Classic Wave Fragrance Collection",
  accountNumber: "8085597947"
};

export const PRODUCTS: Product[] = [

  // ─── PERFUMES ────────────────────────────────────────────────────────────────

  { id: 'p-storm-elixir-inferno', name: 'Storm Elixir – Inferno', price: 41800, category: Category.PERFUME, gender: Gender.MALE, description: 'A powerful fiery blend of spices and dark woods for the ultimate presence.', notes: 'Oud, Saffron, Leather', imageUrl: '/images/storm-elixir-inferno.jpg' },
  { id: 'p-storm-elixir-zeus', name: 'Storm Elixir – Zeus', price: 41800, category: Category.PERFUME, gender: Gender.MALE, description: 'Electrifying, bold and commanding. Built for the gods.', notes: 'Bergamot, Amber, Cedarwood', imageUrl: '/images/storm-elixir-zeus.jpg' },
  { id: 'p-auenios-luxury', name: 'Auenios for Him (Perfume)', price: 22300, category: Category.PERFUME, gender: Gender.MALE, description: 'Inspired by greatness. A sophisticated blend of pineapple and birch.', notes: 'Pineapple, Birch, Musk', imageUrl: 'https://m.media-amazon.com/images/I/51gEvhn5U8L.jpg' },
  { id: 'p-ak-for-men', name: 'AK for Men (Perfume)', price: 16670, category: Category.PERFUME, gender: Gender.MALE, description: 'A distinctive strong masculine fragrance built for confidence.', notes: 'Cedarwood, Vetiver, Musk', imageUrl: '/images/24k-homme-perfume.jpg' },
  { id: 'p-riggs-perfume', name: 'Riggs Luxury Perfume', price: 14000, category: Category.PERFUME, gender: Gender.MALE, description: 'The signature Riggs experience in a high-concentration parfum.', notes: 'Vetiver, Cedar, Citrus', imageUrl: '/images/riggs-perfume-collection.jpg' },
  { id: 'p-chocolate-musk-new', name: 'Chocolate Musk (New Edition)', price: 11000, category: Category.PERFUME, gender: Gender.FEMALE, description: 'A decadent rich gourmand experience that lingers on the skin.', notes: 'Dark Chocolate, Vanilla, Musk', imageUrl: 'https://m.media-amazon.com/images/I/61cXmYocR-L._AC_UF1000,1000_QL80_.jpg' },
  { id: 'p-huga', name: 'Hugo Boss (Perfume)', price: 9000, category: Category.PERFUME, gender: Gender.MALE, description: 'The iconic scent of the modern gentleman. Timeless, fresh and sophisticated.', notes: 'Apple, Geranium, Cedarwood', imageUrl: '/images/hugo-boss-bottled.jpeg' },
  { id: 'p-smart-perfume', name: 'Smart (Perfume)', price: 7500, category: Category.PERFUME, gender: Gender.MALE, description: 'A smart refined scent for the modern intellectual.', notes: 'Woody, Aromatic, Fresh', imageUrl: '/images/smart-collection-174.jpeg' },
  { id: 'p-creed', name: 'Creed (Perfume)', price: 7000, category: Category.PERFUME, gender: Gender.MALE, description: 'A masterpiece of citrus and woods. Timeless luxury.', notes: 'Bergamot, Oakmoss, Amber', imageUrl: '/images/creed-aventus.jpg' },
  { id: 'p-moussupp', name: 'Mousuf (Perfume)', price: 4770, category: Category.PERFUME, gender: Gender.MALE, description: 'Long-lasting and intense. A cult favourite on campus.', notes: 'Oud, Musk, Spice', imageUrl: '/images/mousuf-perfume.jpeg' },
  { id: 'p-my-dear-body', name: 'My Dear Body (Perfume)', price: 4400, category: Category.PERFUME, gender: Gender.FEMALE, description: 'Light and airy with a feminine floral heart.', notes: 'Jasmine, Peony, Musk', imageUrl: '/images/my-dear-body-combo.jpg' },
  { id: 'p-smart-world-asad', name: 'Smart World Asad (Perfume)', price: 4000, category: Category.PERFUME, gender: Gender.MALE, description: 'A global blend — sharp clean and commanding.', notes: 'Citrus, Vetiver, Sandalwood', imageUrl: '/images/azad-smart-world.jpeg' },
  { id: 'p-matador-intense', name: 'Matador – Intense', price: 3600, category: Category.PERFUME, gender: Gender.MALE, description: 'Bold and unapologetic. Spicy depth with an intense dry-down.', notes: 'Black Pepper, Oud, Tobacco', imageUrl: '/images/matador-intense.jpeg' },
  { id: 'p-nora-pink', name: 'Nora Pink (Perfume)', price: 3600, category: Category.PERFUME, gender: Gender.FEMALE, description: 'Soft sweet and youthful. A blossoming floral dream.', notes: 'Pink Pepper, Rose, White Musk', imageUrl: '/images/nora-pink.jpeg' },
  { id: 'p-emergency', name: 'Emergency (Perfume)', price: 3600, category: Category.PERFUME, gender: Gender.MALE, description: 'Fresh and impactful. Built for the busy lifestyle.', notes: 'Citrus, Green, Woody', imageUrl: '/images/emergency-perfume.jpeg' },
  { id: 'p-sens', name: 'Sens (Perfume)', price: 1620, category: Category.PERFUME, gender: Gender.FEMALE, description: 'An accessible everyday scent with a warm soft character.', notes: 'Floral, Musk, Light Woody', imageUrl: '/images/sens-perfume.jpeg' },

  // ─── BODY SPRAYS ─────────────────────────────────────────────────────────────

  { id: 'bs-rexona', name: 'Rexona (Body Spray)', price: 8250, category: Category.BODY_SPRAY, gender: Gender.MALE, description: '72h protection with motion-sensing technology.', notes: 'Fresh, Clean, Sport', imageUrl: '/images/rexona-collection.jpeg' },
  { id: 'bs-fogg-amber-oud', name: 'Fogg – Intense Oud', price: 7500, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'Premium Fogg with rich Oud and Amber — long-lasting luxury.', notes: 'Amber, Oud, Exotic Woods', imageUrl: '/images/fogg-intense-oud.jpeg' },
  { id: 'bs-fogg-gala-noire', name: 'Fogg – Fresh Fougere', price: 7500, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'Dark intense Fogg variant — a night-out essential.', notes: 'Dark Musk, Spice, Woody', imageUrl: '/images/fogg-fresh-fougere.jpeg' },
  { id: 'bs-fogg-fusion', name: 'Fogg – Pure Fusion', price: 7500, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'A fusion of fresh and oriental notes that lasts all day.', notes: 'Citrus, Sandalwood, Musk', imageUrl: '/images/fogg-pure-fusion.jpeg' },
  { id: 'bs-24k-gold', name: '24K – Gold', price: 6870, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'Opulent rich and warm. Pure liquid gold in a can.', notes: 'Oud, Amber, Saffron', imageUrl: '/images/24k-original-body-spray.jpg' },
  { id: 'bs-24k-white', name: '24K – White', price: 6870, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'Pure clean and crystalline. Luxury in white.', notes: 'White Musk, Iris, Sandalwood', imageUrl: '/images/24k-perfume-collection.jpg' },
  { id: 'bs-24k-black', name: '24K – Black', price: 6870, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'Dark mysterious and commanding. The boldest of the trio.', notes: 'Black Musk, Leather, Oud', imageUrl: '/images/24k-perfume-collection.jpg' },
  { id: 'bs-explore', name: 'Explore (Body Spray)', price: 5000, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'Adventure in a can. Fresh and woody with great throw.', notes: 'Aquatic, Cedar, Bergamot', imageUrl: '/images/explore-edp.jpeg' },
  { id: 'bs-karis', name: 'Karis (Body Spray)', price: 4999, category: Category.BODY_SPRAY, gender: Gender.FEMALE, description: 'Delicate and floral with excellent longevity for everyday wear.', notes: 'Floral, Fruity, Musk', imageUrl: '/images/karis-collection.jpeg' },
  { id: 'bs-nivea-bw', name: 'Nivea Black & White (Body Spray)', price: 5000, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'No white marks on black no yellow stains on white.', notes: 'Anti-Stain, Fresh, Clean', imageUrl: 'https://m.media-amazon.com/images/I/61ntSCjIeML.jpg' },
  { id: 'bs-nivea-men-dry-bs', name: 'Nivea Men Dry (Body Spray)', price: 2700, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'Effective everyday dry protection with a clean masculine scent.', notes: 'Clean, Dry, Masculine', imageUrl: '/images/nivea-men-dry.jpeg' },
  { id: 'bs-nivea-men-deep', name: 'Nivea Men Deep (Body Spray)', price: 4800, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'Deep Black Carbon notes for ultimate masculine freshness.', notes: 'Black Carbon, Darkwood, Musk', imageUrl: '/images/nivea-men-deep.jpeg' },
  { id: 'bs-elements', name: 'Elements (Body Spray)', price: 4940, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'Inspired by the raw power of nature. Bold and elemental.', notes: 'Woody, Earth, Vetiver', imageUrl: '/images/elements-body-spray.jpeg' },
  { id: 'bs-hug-dear-body', name: 'Hug – Dear Body', price: 4640, category: Category.BODY_SPRAY, gender: Gender.FEMALE, description: 'A warm comforting embrace in fragrance form.', notes: 'Soft Floral, Vanilla, Musk', imageUrl: '/images/hug-body-spray.jpeg' },
  { id: 'bs-brut', name: 'Brut (Body Spray)', price: 4600, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'The classic gentleman spray. Timeless and dependable.', notes: 'Fougere, Lavender, Oakmoss', imageUrl: '/images/brut-deodorant.jpeg' },
  { id: 'bs-smart', name: 'Smart (Body Spray)', price: 4540, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'Crisp and intelligent. Stays fresh from morning to night.', notes: 'Green, Aqua, Musk', imageUrl: '/images/smart-body-spray.jpeg' },
  { id: 'bs-fogg-standard', name: 'Fogg (Body Spray)', price: 4400, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'The original Fogg — no gas all perfume.', notes: 'Fresh, Citrus, Light Woody', imageUrl: '/images/fogg-standard.jpeg' },
  { id: 'bs-moussupp-bs', name: 'Mousuf (Body Spray)', price: 4000, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'The popular Mousuf formula in an easy aerosol spray.', notes: 'Oud, Musk, Spice', imageUrl: '/images/mousuf-body-spray.jpg' },
  { id: 'bs-choco-musk-can', name: 'Choco Musk (Can)', price: 3950, category: Category.BODY_SPRAY, gender: Gender.FEMALE, description: 'Al-Rehab inspired chocolate musk body spray in a sleek can.', notes: 'Chocolate, Musk, Vanilla', imageUrl: '/images/choco-musk-can.jpg' },
  { id: 'bs-bakarat', name: 'Baccarat (Body Spray)', price: 3740, category: Category.BODY_SPRAY, gender: Gender.FEMALE, description: 'Baccarat Rouge-inspired — amber and jasmine in a convenient spray.', notes: 'Amber, Jasmine, Saffron', imageUrl: '/images/barakkat-rouge-540.webp' },
  { id: 'bs-confetti-diva', name: 'Confetti – Diva', price: 3700, category: Category.BODY_SPRAY, gender: Gender.FEMALE, description: 'Glamorous and vibrant. Own every room you walk into.', notes: 'Floral, Berry, Musk', imageUrl: '/images/confetti-diva.jpg' },
  { id: 'bs-confetti-chocolate', name: 'Confetti – Chocolate', price: 3700, category: Category.BODY_SPRAY, gender: Gender.FEMALE, description: 'Sweet warm chocolate notes for a deliciously feminine finish.', notes: 'Chocolate, Caramel, Musk', imageUrl: '/images/confetti-chocolate.jpg' },
  { id: 'bs-confetti-maple', name: 'Confetti – Maple', price: 3700, category: Category.BODY_SPRAY, gender: Gender.FEMALE, description: 'A sweet comforting gourmand scent with a subtle woody base.', notes: 'Maple, Vanilla, Cedar', imageUrl: '/images/confetti-maple.jpg' },
  { id: 'bs-confetti-coral', name: 'Confetti – Coral', price: 3700, category: Category.BODY_SPRAY, gender: Gender.FEMALE, description: 'Fresh and oceanic with a feminine floral twist.', notes: 'Aquatic, Coral, White Musk', imageUrl: '/images/confetti-coral.jpg' },
  { id: 'bs-confetti-pretty', name: 'Confetti – Pretty', price: 3700, category: Category.BODY_SPRAY, gender: Gender.FEMALE, description: 'Light airy and effortlessly charming for daily wear.', notes: 'Peach, Rose, Soft Musk', imageUrl: '/images/confetti-pretty.jpg' },
  { id: 'bs-riggs-cecho', name: 'Riggs – Echo', price: 3700, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'Sharp and echoing. A scent that follows you everywhere.', notes: 'Fougere, Vetiver, Musk', imageUrl: '/images/riggs-echo.jpg' },
  { id: 'bs-riggs-voyage', name: 'Riggs – Voyage', price: 3700, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'Adventurous and aquatic. A journey in every spray.', notes: 'Aquatic, Bergamot, Cedarwood', imageUrl: '/images/riggs-voyage.jpg' },
  { id: 'bs-riggs-rustic', name: 'Riggs – Rustic', price: 3700, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'Raw earth and wood. Grounded and authentic.', notes: 'Oakmoss, Sandalwood, Earth', imageUrl: '/images/riggs-rustic.jpg' },
  { id: 'bs-riggs-patrol', name: 'Riggs – Patrol', price: 3700, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'Commanding and authoritative. Designed for the go-getter.', notes: 'Leather, Cedar, Black Pepper', imageUrl: '/images/riggs-patrol.jpg' },
  { id: 'bs-riggs-power', name: 'Riggs – Power', price: 3700, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'Maximum impact maximum freshness.', notes: 'Citrus, Aromatic, Musk', imageUrl: '/images/riggs-power.jpg' },
  { id: 'bs-riggs-only', name: 'Riggs – Only', price: 3700, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'Subtle and clean. An everyday signature.', notes: 'Green, Aqua, Soft Musk', imageUrl: '/images/riggs-only.jpg' },
  { id: 'bs-riggs-ace', name: 'Riggs – Ace', price: 3700, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'A winning combination of freshness and confidence.', notes: 'Bergamot, Woody, Musk', imageUrl: '/images/riggs-ace.jpg' },
  { id: 'bs-riggs-rider', name: 'Riggs – Rider', price: 3700, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'Ride through the day in style with this bold fragrance.', notes: 'Leather, Spice, Cedar', imageUrl: '/images/riggs-rider.jpg' },
  { id: 'bs-riggs-icon', name: 'Riggs – Icon', price: 3700, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'Be iconic. A legendary scent for legends in the making.', notes: 'Amber, Tobacco, Musk', imageUrl: '/images/riggs-icon.jpg' },
  { id: 'bs-armour', name: 'Armour (Body Spray)', price: 3700, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'Protection meets style. A shielding masculine scent.', notes: 'Metallic, Woody, Musk', imageUrl: '/images/riggs-armour.jpg' },
  { id: 'bs-venom', name: 'Venom (Body Spray)', price: 3700, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'Dangerously good. A dark edgy scent with real bite.', notes: 'Black Pepper, Oud, Dark Musk', imageUrl: '/images/riggs-venom.jpg' },
  { id: 'bs-my-dear-body', name: 'My Dear Body (Body Spray)', price: 3600, category: Category.BODY_SPRAY, gender: Gender.FEMALE, description: 'Gentle and feminine. A soft daily body spray.', notes: 'Floral, Light Musk, Fresh', imageUrl: '/images/my-dear-body-collection.jpg' },
  { id: 'bs-dove', name: 'Dove Men+Care (Body Spray)', price: 3600, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'Clean comfort all day. The trusted Dove experience.', notes: 'Clean, Comfort, Fresh', imageUrl: 'https://m.media-amazon.com/images/I/9135Rtp5wcL.jpg' },
  { id: 'bs-osca', name: 'Osca (Body Spray)', price: 3600, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'A smooth everyday masculine fragrance with lasting freshness.', notes: 'Aqua, Woody, Musk', imageUrl: '/images/osca-body-spray.jpg' },
  { id: 'bs-galaxy-s3', name: 'Galaxy S III (Body Spray)', price: 3400, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'Futuristic freshness inspired by innovation and technology.', notes: 'Aquatic, Citrus, Clean Musk', imageUrl: '/images/galaxy-s3-body-spray.jpg' },
  { id: 'bs-auenios-bs', name: 'Aventos for Him (Body Spray)', price: 3430, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'Aventus-inspired body spray — pineapple and birch in a convenient can.', notes: 'Pineapple, Birch, Musk', imageUrl: '/images/aventos-for-him.jpg' },
  { id: 'bs-bellus', name: 'Bellus (Body Spray)', price: 3370, category: Category.BODY_SPRAY, gender: Gender.FEMALE, description: 'Beautifully fragrant. A graceful feminine body spray.', notes: 'Rose, Iris, Soft Musk', imageUrl: '/images/bellus-collection.jpg' },
  { id: 'bs-axe-dark-temptation', name: 'Axe – Dark Temptation', price: 3200, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'Irresistibly dark chocolate notes — Axe most iconic scent.', notes: 'Dark Chocolate, Amber, Musk', imageUrl: '/images/axe-dark-temptation.jpg' },
  { id: 'bs-axe-black', name: 'Axe – Black', price: 3200, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'Clean refined and effortlessly masculine. Pure simplicity.', notes: 'Frozen Pear, Cardamom, Cedarwood', imageUrl: '/images/axe-black.jpg' },
  { id: 'bs-axe-marine', name: 'Axe – Marine', price: 3200, category: Category.BODY_SPRAY, gender: Gender.MALE, description: 'Dive into freshness. An aquatic oceanic experience.', notes: 'Sea Salt, Aqua, Citrus', imageUrl: '/images/axe-marine.jpg' },
  { id: 'bs-chocolate-musk-bs', name: 'Chocolate Musk (Body Spray)', price: 11830, category: Category.BODY_SPRAY, gender: Gender.FEMALE, description: 'Rich chocolate musk in a premium body spray format.', notes: 'Dark Chocolate, Musk, Vanilla', imageUrl: 'https://m.media-amazon.com/images/I/61cXmYocR-L._AC_UF1000,1000_QL80_.jpg' },

  // ─── ROLL-ONS (NIVEA) ────────────────────────────────────────────────────────

  { id: 'ro-nivea-bw-clear-f', name: 'Nivea B&W Invisible Clear', price: 5000, category: Category.ROLL_ON, gender: Gender.FEMALE, description: 'No white marks on black no yellow stains on white.', notes: 'Invisible, Anti-Stain', imageUrl: 'https://m.media-amazon.com/images/I/51BBeO0yhSL._AC_SL1500_.jpg' },
  { id: 'ro-nivea-dry-comfort-f', name: 'Nivea Dry Comfort', price: 2700, category: Category.ROLL_ON, gender: Gender.FEMALE, description: '72h powerful protection against sweat and body odor.', notes: 'Dry, Reliable, Fresh', imageUrl: '/images/nivea-dry-comfort.jpg' },
  { id: 'ro-nivea-pearl-beauty-f', name: 'Nivea Pearl & Beauty', price: 3000, category: Category.ROLL_ON, gender: Gender.FEMALE, description: 'Precious pearl extracts for smooth beautiful underarms.', notes: 'Pearl Extracts, Soft', imageUrl: '/images/nivea-pearl-beauty.jpg' },
  { id: 'ro-nivea-fresh-natural-f', name: 'Nivea Fresh Natural', price: 3000, category: Category.ROLL_ON, gender: Gender.FEMALE, description: 'Refreshing ocean extracts for a naturally fresh all-day feeling.', notes: 'Ocean Extracts, Marine', imageUrl: '/images/nivea-fresh-natural.jpg' },
  { id: 'ro-nivea-energy-fresh-f', name: 'Nivea Energy Fresh', price: 3000, category: Category.ROLL_ON, gender: Gender.FEMALE, description: 'Energizing freshness with lemongrass extract for an active day.', notes: 'Lemongrass, Zesty', imageUrl: 'https://m.media-amazon.com/images/I/61++-u0ImUL._AC_SL1500_.jpg' },
  { id: 'ro-nivea-fresh-sensation-f', name: 'Nivea Fresh Sensation', price: 3000, category: Category.ROLL_ON, gender: Gender.FEMALE, description: 'Infinite freshness with anti-bacterial formula and lasting scent.', notes: 'Floral, Fresh, Clean', imageUrl: '/images/nivea-fresh-sensation.jpg' },
  { id: 'ro-nivea-men-deep-carbon', name: 'Nivea Men Deep Carbon', price: 4000, category: Category.ROLL_ON, gender: Gender.MALE, description: 'Deep Black Carbon and Darkwood notes for ultimate masculine freshness.', notes: 'Black Carbon, Darkwood', imageUrl: '/images/nivea-men-deep-darkwood.jpg' },
  { id: 'ro-nivea-men-cool-kick', name: 'Nivea Men Cool Kick', price: 3000, category: Category.ROLL_ON, gender: Gender.MALE, description: 'Revitalizing cooling freshness for 48 hours.', notes: 'Icy Chill, Mint', imageUrl: 'https://m.media-amazon.com/images/I/61++-u0ImUL._AC_SL1500_.jpg' },
  { id: 'ro-nivea-men-bw-invisible', name: 'Nivea Men B&W Invisible', price: 5000, category: Category.ROLL_ON, gender: Gender.MALE, description: 'Original anti-stain protection for black and white clothes.', notes: 'Anti-Stain, Power Fresh', imageUrl: 'https://m.media-amazon.com/images/I/51BBeO0yhSL._AC_SL1500_.jpg' },
  { id: 'ro-nivea-men-dry-fresh', name: 'Nivea Men Dry Fresh', price: 3000, category: Category.ROLL_ON, gender: Gender.MALE, description: 'Powerful 72h protection tested in real-life situations.', notes: 'Dual Active, Extra Dry', imageUrl: '/images/nivea-men-dry-fresh.jpg' },
  { id: 'ro-nivea-men-dry-impact', name: 'Nivea Men Dry Impact', price: 2700, category: Category.ROLL_ON, gender: Gender.MALE, description: 'Minerals for a long-lasting dry feeling all day.', notes: 'Minerals, Dry Protection', imageUrl: 'https://m.media-amazon.com/images/I/615m2gL-BBL._AC_SL1500_.jpg' },

  // ─── VIP EXCLUSIVE DESIGNER COLLECTION ─────────────────────────────────────
  // Shown only on /vip — hidden from regular category browsing (see CategoryPage.tsx)

  { id: 'vip-tf-black-orchid', name: 'Tom Ford – Black Orchid (100mL)', price: 249500, category: Category.PERFUME, gender: Gender.FEMALE, description: 'An opulent, sensual blend of black truffle and orchid wrapped in dark, mysterious luxury.', notes: 'Black Truffle, Orchid, Patchouli', imageUrl: '/images/vip/tf-black-orchid.jpg', vip: true },
  { id: 'vip-tf-ombre-leather', name: 'Tom Ford – Ombré Leather (100mL)', price: 258000, category: Category.PERFUME, gender: Gender.MALE, description: 'Sleek suede leather wrapped in warm amber and spice — modern, unisex sophistication.', notes: 'Cardamom, Leather, Amber', imageUrl: '/images/vip/tf-ombre-leather.jpg', vip: true },
  { id: 'vip-tf-noir-extreme', name: 'Tom Ford – Noir Extreme (100mL)', price: 355000, category: Category.PERFUME, gender: Gender.MALE, description: 'An intense oriental blend of warm spice and rich vanilla for the boldest presence.', notes: 'Saffron, Vanilla, Rosewood', imageUrl: '/images/vip/tf-noir-extreme.jpg', vip: true },
  { id: 'vip-tf-tobacco-vanille', name: 'Tom Ford – Tobacco Vanille (100mL)', price: 735000, category: Category.PERFUME, gender: Gender.MALE, description: "The house's most iconic creation — rich tobacco leaf wrapped in warm vanilla and spice.", notes: 'Tobacco Leaf, Vanilla, Dried Fruit', imageUrl: '/images/vip/tf-tobacco-vanille.jpg', vip: true },
  { id: 'vip-ysl-y', name: 'Yves Saint Laurent – Y (100mL)', price: 197000, category: Category.PERFUME, gender: Gender.MALE, description: 'A fresh aromatic statement of self-made confidence — sharp, clean, and modern.', notes: 'Bergamot, Sage, Cedarwood', imageUrl: '/images/vip/ysl-y.jpg', vip: true },
  { id: 'vip-jc-man-extreme', name: 'Jimmy Choo – Man Extreme (100mL)', price: 108000, category: Category.PERFUME, gender: Gender.MALE, description: 'A bold, energetic woody scent for the man who commands every room.', notes: 'Ginger, Pink Pepper, Woods', imageUrl: '/images/vip/jc-man-extreme.jpg', vip: true },
  { id: 'vip-jc-illicit', name: 'Jimmy Choo – Illicit (100mL)', price: 198000, category: Category.PERFUME, gender: Gender.FEMALE, description: 'A daringly seductive floral fruity scent for the fearless and free-spirited.', notes: 'Fig Nectar, Honeysuckle, Woody Musk', imageUrl: '/images/vip/jc-illicit.jpg', vip: true },
  { id: 'vip-dior-sauvage', name: 'Dior – Sauvage (100mL)', price: 295000, category: Category.PERFUME, gender: Gender.MALE, description: 'A radically fresh composition under a sky drenched with light — raw and noble at once.', notes: 'Bergamot, Pepper, Ambroxan', imageUrl: '/images/vip/dior-sauvage.jpg', vip: true },
  { id: 'vip-armani-stronger-intensely', name: 'Emporio Armani – Stronger With You Intensely (100mL)', price: 225000, category: Category.PERFUME, gender: Gender.MALE, description: 'A warmer, more intense take on the modern romantic — rich amber wrapped in toffee and spice.', notes: 'Pink Pepper, Toffee, Cedarwood', imageUrl: '/images/vip/armani-stronger-intensely.jpg', vip: true },
  { id: 'vip-armani-acqua-di-gio', name: 'Giorgio Armani – Acqua Di Giò Pour Homme (100mL)', price: 168000, category: Category.PERFUME, gender: Gender.MALE, description: 'The definitive aquatic masculine — crisp marine freshness that defined a generation.', notes: 'Bergamot, Jasmine, Patchouli', imageUrl: '/images/vip/armani-acqua-di-gio.jpg', vip: true },
  { id: 'vip-ck-eternity', name: 'Calvin Klein – Eternity (100mL)', price: 132000, category: Category.PERFUME, gender: Gender.FEMALE, description: "The brand's timeless heritage classic — a refined floral woven with warm amber and sandalwood.", notes: 'Freesia, Sandalwood, Amber', imageUrl: '/images/vip/ck-eternity.jpg', vip: true },
];
